(global-font-lock-mode t)
(display-time)
(line-number-mode t)
(column-number-mode t)

(setq make-backup-files nil)
(setq inhibit-startup-message t) 
(setq initial-scratch-message "")
(setq next-line-add-newlines nil)
(setq require-final-newline t)
(setq max-lisp-eval-depth 10000)
(setq vc-handled-backends ())

(setq-default transient-mark-mode t)
(setq-default tab-width 2)
(setq-default indent-tabs-mode nil)
