(add-hook 'rust-mode-hook
          '(lambda ()
             (when (executable-find "racer")
               (make-local-variable 'ac-stop-words)
               (add-to-list 'ac-stop-words "")
               (setq ac-auto-start 2)
               (ac-racer-setup)
               )
             (when (executable-find "rustfmt")
               (setq rust-format-on-save t))))
